### ISSUE TITLE
I can't get right results.

### ISSUE THREAD

**Issue by andyW296** [gkc1000/potato#3]
Hi, I use the code calculate Single-site DMFT with 9 bath sites system in RCCSD(I hope to reproduce the results in the paper of PHYSICAL REVIEW B 100, 115154 (2019)). And i use: 
nx=50
U=2
nw=9
mydmft, w, delta = dmft.hub_1d (nx, U, nw)
freqs = _get_linear_freqs(-5., 5., 128)[0]
ldos = mydmft.get_ldos(freqs, delta)
But the ldos can't have a good match with the paper results in the paper of FIG. 1.
![results](https://github.com/gkc1000/potato/assets/77146790/0dbc2c2c-da70-4373-9c01-0d9c4400d003)

Where did I go wrong？

**Comment by zhutianyu1991** [comment]
The results in our PRB 2019 paper were generated with bath discretization on a Gauss-Legendre quadrature, so one should use _get_scaled_legendre_roots (not linear discretization get_linear_freqs). One useful example might be https://github.com/gkc1000/potato/blob/0.2/examples/hub_1d.py

Please also follow the parameters described in the original paper: "The bath energies and weights used to discretize the hybridization are chosen according to Gauss-Legendre quadrature on the interval [−7t + U/2, +7t + U/2] for the 1D Hubbard model and [−9t + U/2, +9t + U/2] for the 2D Hubbard model. In almost all calculations, we achieve convergence using a small imaginary broadening η/t = 0.1."

**Comment by andyW296** [comment]
Thank you for your help！

**Comment by tberkel** [comment]
Also, make sure to use branch 0.2, not the master branch. Branch 0.2 is much more updated.

**Comment by andyW296** [comment]
Thank you! 
The results calculated using branch 0.2 are very close to the results in the paper.
![image](https://github.com/gkc1000/potato/assets/77146790/f4d2b8a4-c774-48e5-b67e-a37abdd0bf43)
![image](https://github.com/gkc1000/potato/assets/77146790/5804fe56-88fb-4b29-a73a-641dcb90135c)
